### ISSUE TITLE
TODO for firebase-shorten-url

### ISSUE THREAD

**Issue by duyetdev** [duyetdev/firebase-shorten-url#94]
- [x] Auto create after pasting the link
- [x] Update UI ant.design
- [ ] Analytics usage

**Comment by duyetdev** [comment]
- [ ] Analytics usage => I'm lười vkl, skip that
